### PR TITLE
Add support for :action attributes. Closes #29

### LINKED ISSUE #29: New {{action}} syntax in Ember
The syntax of the {{action}} helper was recently changed ([83b7a61a](https://github.com/emberjs/ember.js/commit/83b7a61a892e55423cf1e66f606b13435bcab8f0)), so Hamlbars doesn't work with Ember master anymore.

Should we just update it to use the `context` option as the first argument to {{action}}?

I'm honestly a bit unhappy with the verbosity of our current syntax, so I wonder if we should improve it along with this change.

Right now we have

```
event: {action: 'edit', context: 'model'}
```

to yield

```
{{action edit context="model"}} // old
{{action edit model}} // new
```

How about this instead?

```
action: 'edit model'
```

So there's no surrounding `event`. We lose the ability to have multiple actions, but at least in Ember, this [isn't supported anyway](http://stackoverflow.com/questions/11544565/ember-handling-multiple-events-with-action-tag) to my understanding.

Options could be inline, like so:

```
action: 'edit model href=true'
```

### PR DESCRIPTION
**Pull request by joliss**
Development graciously sponsored by Funding Gates.

(Copyright is still owned and licensed to the project by me.)

### CODE REVIEW

**Comment by joliss** [comment]
I rebased this on master, so it should merge again. :)

**Comment by artzte** [comment]
Be great to get the new action syntax support so we can move on to 1.0... thanks joliss.

**Comment by jimsynz** [comment]
This is epic work Jo! Thanks so much. Did you have any ideas about @artzte's comment on #29?

**Comment by joliss** [comment]
> There is an unfortunate collision with form action attributes with this. How about calling it ember-action or just use the old event keyword with a plain string with the new syntax?

Blimey - good catch.

I'm not a super-big fan of `event` when it doesn't have a nested `action` attribute anymore, because now we're 1:1-mapping `action` on the handlebars side to `event` on the hamlbars side. It's possible to do for sure, but it seems like unnecessary mental overhead.

For that reason, what do you guys think of `hb_action`? Or `_action`? If there's ever any need for other attribute helpers, we can form them by analogy, like `hb_bindAttr` or `_bindAttr`. Not that we need that particular one.

Thoughts?

**Comment by artzte** [comment]
Jo, I like the _&lt;helper-attribute-name&gt; convention because it is succinct.

**Comment by jimsynz** [comment]
I can live with `em_event` or `_event`. Remember that these are Ember specific features and there are a bunch of people who use Hamlbars for standalone Handlebars templating.   

That said, I'm sitting in a hotel in Wellington with no wifi, so you guys can pretty much get away with anything you want :)  

## 

James Harton
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by joliss** [comment]
They're not _necessarily_ Ember-specific though, right? In principle, I mean. All we're doing is dumping `{{#{key} #{value}}}` into the attributes.

So, um, how about `_action`? @jamesotron, will that work for you?

If there's ever need for more helpers (`{{foo}}`), we can add them analogously (`_foo`) or even make a catch-all `/_.*/`, but for now it seems sensible to stick with `action` only.

**Comment by jacquescrocker** [comment]
+1 for `_action`. I think the catch-all on `/_.*/` would be a great solution too

**Comment by jimsynz** [comment]
Works for me. @joliss do you want to throw in another commit?

**Comment by joliss** [comment]
Done.

**Comment by jimsynz** [comment]
Awesome. Should I bump version? I think so.

**Comment by joliss** [comment]
Yeah, I'd suggest going to 1.1.0.

Thanks for merging!

**Comment by jimsynz** [comment]
That's exactly what I was thinking :)  

## 

James Harton
sociable.co.nz
@jamesotron
+64226803869

**Comment by jimsynz** [comment]
Just a quick note @joliss; when you include matches from a fairly recent version of rspec you should put a minimum version on the dependencies in the gemspec. Not a biggy, just something to remember next time :)

**Comment by joliss** [comment]
Thanks for the quick release, you're awesome! I'll go and use this in my client's project now :)

Re RSpec, out of curiosity and not to nitpick, but did it actually fail? I would've expected this to work in any version, since #start_with? is a String method (`'asdf'.start_with? 'as' => true`). The RSpec start_with/end_with support seems to be about arrays.

**Comment by jimsynz** [comment]
It was failing for me until I forced bundler to use a newer version.

## 

James Harton
sociable.co.nz
@jamesotron
+64226803869

**Pull request merged**
