### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by joliss**
- Build with MRI 1.8.7 and 1.9.3 on Travis
- Add Travis badge

This likely requires #18 to be merged first.

### CODE REVIEW

**Comment by joliss** [comment]
Thanks for merging. Remember to flick the switch on http://travis-ci.org/profile so it actually gets built.

**Comment by jimsynz** [comment]
Yup. Cheers.

**Comment by joliss** [comment]
Hm, it's not being built yet? http://travis-ci.org/#!/jamesotron/hamlbars

**Comment by jimsynz** [comment]
I've just fixed it now.

**Pull request merged**
