### PR TITLE
preliminary attempt at getting it working on both Haml 3.1 and 3.2

### PR DESCRIPTION
**Pull request by jacquescrocker**
this fix seems to get it working on my project with Haml 3.2 but i'll use it in prod for a little while and let you know

### CODE REVIEW

**Comment by jimsynz** [comment]
Thanks for the contribution - I'll take a look some time over the next couple of days.

**Comment by jimsynz** [comment]
Hey there. I manually ran the specs against haml 3.2.0.beta.1 and got the following failure:

```
Failures:

  1) Hamlbars::Template should bind element attributes
     Failure/Error: template.render.should == "Handlebars.templates[\"#{Hamlbars::Template.path_translator(File.basename(template_file.path))}\"] = Handlebars.compile(\"<img {{bindAttr src=\\\"logoUri\\\"}} alt=\\'Logo\\' />\");\n"
       expected: "Handlebars.templates[\"hamlbars_template20120808_69668_1dewk5b\"] = Handlebars.compile(\"<img {{bindAttr src=\\\"logoUri\\\"}} alt=\\'Logo\\' />\");\n"
            got: "Handlebars.templates[\"hamlbars_template20120808_69668_1dewk5b\"] = Handlebars.compile(\"<img {{bindAttr src=\\\"logoUri\\\"}} alt=\\'Logo\\'>\");\n" (using ==)
       Diff:
       @@ -1,2 +1,2 @@
       -Handlebars.templates["hamlbars_template20120808_69668_1dewk5b"] = Handlebars.compile("<img {{bindAttr src=\"logoUri\"}} alt=\'Logo\' />");
       +Handlebars.templates["hamlbars_template20120808_69668_1dewk5b"] = Handlebars.compile("<img {{bindAttr src=\"logoUri\"}} alt=\'Logo\'>");
     # ./spec/template_spec.rb:35:in `block (2 levels) in <top (required)>'

Finished in 0.48257 seconds
34 examples, 1 failure

Failed examples:

rspec ./spec/template_spec.rb:31 # Hamlbars::Template should bind element attributes
```

**Comment by jimsynz** [comment]
Which is pretty strange that haml would change their HTML output. WAT?

**Comment by jacquescrocker** [comment]
heh, yeah. Looks like Haml changed their output. I'll fix the spec to support both 3.1 and 3.2

**Comment by jimsynz** [comment]
Cheers. That's super awesome.   

## 

James Harton
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by jacquescrocker** [comment]
Ah, they just made the default :html5 instead of :xhtml. i added an explicit format option to that spec to make it pass in both 3.1 and 3.2.beta

https://github.com/haml/haml/blob/master/CHANGELOG.md

**Comment by jacquescrocker** [comment]
sorry, i screwed this pull request up (i should have used topic branches). i'll close, recreate the branches, and then resubmit the pull requests

**Pull request closed without merging**
