### PR TITLE
Rails::Engine check

### PR DESCRIPTION
**Pull request by igoralekseev**
I have an error in this line with Middleman so need to modify

### CODE REVIEW

**Comment by jimsynz** [comment]
Weird. Which ruby is this?

**Comment by jimsynz** [comment]
You should be able to simply use

``` ruby
if defined? Rails::Engine
```

you don't need to check each level in the hierarchy.

**Comment by igoralekseev** [comment]
1. ruby 1.9.3p194 
2. you are right, i didnt know how `defined?` works
3. i've found the bad guy -- https://github.com/wycats/rack-offline/blob/master/lib/rack-offline.rb 
   i use `rack-offline` with Middleman but @wycats likes only rails

**Comment by jimsynz** [comment]
Good luck!

**Pull request closed without merging**
